version: '3.8'

services:
  backend:
    image: ahamednazeer/gs-centric-fanet-routing:be-latest
    container_name: mps-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: ahamednazeer/gs-centric-fanet-routing:fe-latest
    container_name: mps-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
